export const TECHNOLOGY_CONSTRUCTION_LEVEL = {key: 'technology_construction_level', question: 'Berdasarkan daur hidup teknologi terkait dengan tingat kinerja dan berjalannya waktu, berada pada tingkat manakah teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_SUPPORT = {key: 'technology_construction_support', question: 'Pada penggunaan teknologi tersebut, teknologi lain apakah yang mendukung penggunaannya?'}
export const TECHNOLOGY_CONSTRUCTION_ASSESSMENT = {key: 'technology_construction_assessment', question: 'Apakah teknologi tersebut, sebelumnya pernah melalui tahap penilaian teknologi (Technology Assesstment) ?'}
export const TECHNOLOGY_CONSTRUCTION_INNOVATION_CATEGORY = {key: 'technology_construction_innovation_category', question: 'Termasuk dalam kategori inovasi apakah teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_INNOVATION_ORIGIN = {key: 'technology_construction_innovation_origin', question: 'Berasal darimanakah inovasi teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN = {key: 'technology_construction_supply_chain', question: 'Apakah teknologi tersebut memiliki rantai pasok pendukung lain?'}
export const TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN_ORIGIN = {key: 'technology_construction_supply_chain_origin', question: 'Jika Ya, maka berasal darimanakah rantai pasok pendukung tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_HUMAN_RESOURCE = {key: 'technology_construction_human_resource', question: 'Sumber Daya Manusia seperti apakah yang dibutuhkan dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_OBSTACLE = {key: 'technology_construction_obstacle', question: 'Dalam Penggunaan Teknologi tersebut, faktor-faktor apakah yang menjadi kendala dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_ALL_OBSTACLES = {key: 'technology_construction_all_obstacles', question: 'Sebutkan faktor-faktor apa saja yang menjadi kendala dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_SUCCESS_FACTOR = {key: 'technology_construction_success_factor', question: 'Dalam penggunaan teknologi tersebut, faktor-faktor apa saja yang mempengaruhi keberhasilan dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_ALL_SUCCESS_FACTORS = {key: 'technology_construction_all_success_factors', question: 'Sebutkan faktor-faktor apa saja yang mempengaruhi keberhasilan dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_COST = {key: 'technology_construction_cost', question: 'Dalam penggunaan teknologi tersebut, biaya apa saja yang dibutuhkan?'}
export const CONSTRUCTION_PRODUCT_TYPE = {key: 'construction_product_type', question: 'Apakah jenis produk konstruksi yang dihasilkan perusahaan tempat anda bekerja?'} // checkbox
export const TECHNOLOGY_CONSTRUCTION_APPLIED = {key: 'technology_construction_applied', question: 'Teknologi apa yang sudah dan sedang diterapkan oleh perusahaan tempat anda bekerja dalam menghasilkan produk konstruksi?'} // text
export const CONSTRUCTION_PROJECT = {key: 'construction_project', question: 'Di proyek manakah teknologi tersebut digunakan pertama kalinya? (Sebutkan nama proyek beserta lokasi proyek)?'} // text
export const CONSTRUCTION_PROJECT_DATE = {key: 'construction_project_date', question: 'Kapan teknologi tersebut digunakan pertama kalinya? (berdasarkan proyek yang telah disebutkan)'} // date
export const CONSTRUCTION_PROJECT_COST = {key: 'construction_project_cost', question: 'Berapakah jumlah nilai proyek tersebut?'} // radio
export const TECHNOLOGY_CONSTRUCTION_STAGE = {key: 'technology_construction_stage', question: 'Pada tahapan konstruksi apa teknologi tersebut digunakan?'} // checkbox
export const TECHNOLOGY_CONSTRUCTION_TYPE = {key: 'technology_construction_type', question: 'Termasuk dalam jenis teknologi apakah teknologi tersebut?'} // radio
export const TECHNOLOGY_CONSTRUCTION_ORIGIN = {key: 'technology_construction_origin', question: 'Darimana asal mula kepemilikan teknologi tersebut?'} // radio
export const TECHNOLOGY_CONSTRUCTION_OWNER = {key: 'technology_construction_owner', question: 'Siapakah pihak yang memiliki teknologi tersebut?' }// radio
export const TECHNOLOGY_CONSTRUCTION_CATEGORY = {key: 'technology_construction_category', question: 'Menurut ketentuan HaKI (Hak atas Kekayaan Intelektual), termasuk dalam kategori apakah teknologi tersebut?'} // radio
export const TECHNOLOGY_CONSTRUCTION_PRIMARY_TYPE = {key: 'technology_construction_primary_type', question: 'Termasuk dalam jenis teknologi utama apakah teknologi tersebut?'} // radio
export const TECHNOLOGY_CONSTRUCTION_BENEFIT = {key: 'technology_construction_benefit', question: 'Manfaat apa yang didapatkan dari penerapan teknologi tersebut?'} // radio
export const TECHNOLOGY_CONSTRUCTION_ALL_BENEFITS = {key: 'technology_construction_all_benefits', question: 'Sebutkan manfaat apa saja yang didapatkan dari penerapan teknologi tersebut?'} // text
