export const TECHNOLOGY_CONSTRUCTION_LEVEL = {key: 'technology_construction_level', question: 'Berdasarkan daur hidup teknologi terkait dengan tingat kinerja dan berjalannya waktu, berada pada tingkat manakah teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_SUPPORT = {key: 'technology_construction_support', question: '20. Pada penggunaan teknologi tersebut, teknologi lain apakah yang mendukung penggunaannya?'}
export const TECHNOLOGY_CONSTRUCTION_ASSESSMENT = {key: 'technology_construction_assessment', question: 'Apakah teknologi tersebut, sebelumnya pernah melalui tahap penilaian teknologi (technology assessment) ?'}
export const TECHNOLOGY_CONSTRUCTION_INNOVATION_CATEGORY = {key: 'technology_construction_innovation_category', question: 'Termasuk dalam kategori inovasi apakah teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_INNOVATION_ORIGIN = {key: 'technology_construction_innovation_origin', question: 'Berasal darimanakah inovasi teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN = {key: 'technology_construction_supply_chain', question: 'Apakah teknologi tersebut memiliki rantai pasok pendukung lain?'}
export const TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN_ORIGIN = {key: 'technology_construction_supply_chain_origin', question: 'Jika ya, maka berasal darimanakah rantai pasok pendukung tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_HUMAN_RESOURCE = {key: 'technology_construction_human_resource', question: '19. Sumber daya manusia seperti apakah yang dibutuhkan dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_OBSTACLE = {key: 'technology_construction_obstacle', question: '17. Dalam penggunaan teknologi tersebut, faktor-faktor apakah yang menjadi kendala dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_ALL_OBSTACLES = {key: 'technology_construction_all_obstacles', question: '18. Sebutkan faktor-faktor apa saja yang menjadi kendala dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_SUCCESS_FACTOR = {key: 'technology_construction_success_factor', question: '15. Dalam penggunaan teknologi tersebut, faktor-faktor apa saja yang mempengaruhi keberhasilan dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_ALL_SUCCESS_FACTORS = {key: 'technology_construction_all_success_factors', question: '16. Sebutkan faktor-faktor apa saja yang mempengaruhi keberhasilan dalam penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_COST = {key: 'technology_construction_cost', question: '12. Dalam penggunaan teknologi tersebut, biaya apa saja yang dibutuhkan?'}
export const CONSTRUCTION_PRODUCT_TYPE = {key: 'construction_product_type', question: '1. Apakah jenis produk konstruksi yang dihasilkan perusahaan tempat anda bekerja?'}
export const TECHNOLOGY_CONSTRUCTION_APPLIED = {key: 'technology_construction_applied', question: '2. Teknologi apa yang sudah dan sedang diterapkan oleh perusahaan tempat anda bekerja dalam menghasilkan produk konstruksi?'}
export const CONSTRUCTION_PROJECT = {key: 'construction_project', question: '3. Di proyek manakah teknologi tersebut digunakan pertama kalinya? (Sebutkan nama proyek beserta lokasi proyek)?'}
export const CONSTRUCTION_PROJECT_DATE = {key: 'construction_project_date', question: '4. Kapan teknologi tersebut digunakan pertama kalinya? (berdasarkan proyek yang telah disebutkan)'}
export const CONSTRUCTION_PROJECT_COST = {key: 'construction_project_cost', question: '5. Berapakah jumlah nilai proyek tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_STAGE = {key: 'technology_construction_stage', question: '6. Pada tahapan konstruksi apa teknologi tersebut digunakan?'}
export const TECHNOLOGY_CONSTRUCTION_TYPE = {key: 'technology_construction_type', question: '7. Termasuk dalam jenis teknologi apakah teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_ORIGIN = {key: 'technology_construction_origin', question: '8. Darimana asal mula kepemilikan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_OWNER = {key: 'technology_construction_owner', question: '9. Siapakah pihak yang memiliki teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_CATEGORY = {key: 'technology_construction_category', question: '10. Menurut ketentuan HaKI (Hak atas Kekayaan Intelektual), termasuk dalam kategori apakah teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_PRIMARY_TYPE = {key: 'technology_construction_primary_type', question: '11. Termasuk dalam jenis teknologi utama apakah teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_BENEFIT = {key: 'technology_construction_benefit', question: '13. Manfaat apa yang didapatkan dari penerapan teknologi tersebut?'}
export const TECHNOLOGY_CONSTRUCTION_ALL_BENEFITS = {key: 'technology_construction_all_benefits', question: '14. Sebutkan manfaat apa saja yang didapatkan dari penerapan teknologi tersebut?'}
export const INTELLECTUAL_PROPERTY_RIGHT = {key: 'intellectual_property_right', question: 'Termasuk dalam jenis HaKI apakah inovasi teknologi tersebut?'}
