export const TECHNOLOGY_CONSTRUCTION_ASSESSTMENT = 'Apakah teknologi tersebut, sebelumnya pernah melalui tahap penilaian teknologi (Technology Assesstment) ?'
export const TECHNOLOGY_CONSTRUCTION_INOVATION_CATEGORY = 'Termasuk dalam kategori inovasi apakah teknologi tersebut?'
export const TECHNOLOGY_CONSTRUCTION_INOVATION_ORIGIN = 'Berasal darimanakah inovasi teknologi tersebut?'
export const TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN = 'Apakah teknologi tersebut memiliki rantai pasok pendukung lain?'
export const TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN_ORIGIN = 'Jika Ya, maka berasal darimanakah rantai pasok pendukung tersebut?'
export const TECHNOLOGY_CONSTRUCTION_HUMAN_RESOURCE = 'Sumber Daya Manusia seperti apakah yang dibutuhkan dalam penerapan teknologi tersebut?'
export const TECHNOLOGY_CONSTRUCTION_OBSTACLE = 'Dalam Penggunaan Teknologi tersebut, faktor-faktor apakah yang menjadi kendala dalam penerapan teknologi tersebut?'
export const TECHNOLOGY_CONSTRUCTION_ALL_OBSTACLES = 'Sebutkan faktor-faktor apa saja yang menjadi kendala dalam penerapan teknologi tersebut? '
export const TECHNOLOGY_CONSTRUCTION_SUCCESS_FACTOR = 'Dalam penggunaan teknologi tersebut, faktor-faktor apa saja yang mempengaruhi keberhasilan dalam penerapan teknologi tersebut?'
export const TECHNOLOGY_CONSTRUCTION_ALL_SUCCESS_FACTORS = 'Sebutkan faktor-faktor apa saja yang mempengaruhi keberhasilan dalam penerapan teknologi tersebut?'
export const TECHNOLOGY_CONSTRUCTION_COST = 'Dalam penggunaan teknologi tersebut, biaya apa saja yang dibutuhkan?'
export const CONSTRUCTION_PRODUCT_TYPE = 'Apakah jenis produk konstruksi yang dihasilkan perusahaan tempat anda bekerja?' // checkbox
export const APPLIED_TECHNOLOGY_CONSTRUCTION = 'Teknologi apa yang sudah dan sedang diterapkan oleh perusahaan tempat anda bekerja dalam menghasilkan produk konstruksi?' // text
export const FIRST_APPLIED_PR0JECT = 'Di proyek manakah teknologi tersebut digunakan pertama kalinya? (Sebutkan nama proyek beserta lokasi proyek)?' // text
export const FIRST_APPLIED_PROJECT_DATE = 'Kapan teknologi tersebut digunakan pertama kalinya? (berdasarkan proyek yang telah disebutkan)' // date
export const FIRST_APPLIED_PROJECT_VALUE = 'Berapakah jumlah nilai proyek tersebut?' // radio
export const TECHNOLOGY_CONSTRUCTION_STAGE = 'Pada tahapan konstruksi apa teknologi tersebut digunakan?' // checkbox
export const TECHNOLOGY_CONSTRUCTION_TYPE = 'Termasuk dalam jenis teknologi apakah teknologi tersebut?' // radio
export const TECHNOLOGY_CONSTRUCTION_ORIGIN = 'Darimana asal mula kepemilikan teknologi tersebut?' // radio
export const TECHNOLOGY_CONSTRUCTION_OWNER = 'Siapakah pihak yang memiliki teknologi tersebut?' // radio
export const TECHNOLOGY_CONSTRUCTION_CATEGORY = 'Menurut ketentuan HaKI (Hak atas Kekayaan Intelektual), termasuk dalam kategori apakah teknologi tersebut?' // radio
export const TECHNOLOGY_CONSTRUCTION_PRIMARY_TYPE = 'Termasuk dalam jenis teknologi utama apakah teknologi tersebut?' // radio
export const TECHNOLOGY_CONSTRUCTION_BENEFIT = 'Manfaat apa yang didapatkan dari penerapan teknologi tersebut?' // radio
export const TECHNOLOGY_CONSTRUCTION_ALL_BENEFITS = 'Sebutkan manfaat apa saja yang didapatkan dari penerapan teknologi tersebut?' // text
