export const PREFIX = 'PROFILE'

export const PROFILE_ON_CLICK_CREATE_PROFILE = `${PREFIX}_ON_CLICK_CREATE_PROFILE`
export const PROFILE_ON_CLICK_UPDATE_PROFILE = `${PREFIX}_ON_CLICK_UPDATE_PROFILE`
export const PROFILE_GET_PROFILE = `${PREFIX}_GET_PROFILE`
export const PROFILE_SET_COMPANY_NAME = `${PREFIX}_SET_COMPANY_NAME`
export const PROFILE_SET_COMPANY_LOCATION = `${PREFIX}_SET_COMPANY_LOCATION`
export const PROFILE_SET_COMPANY_CATEGORY = `${PREFIX}_SET_COMPANY_CATEGORY`
export const PROFILE_SET_COMPANY_TYPE = `${PREFIX}_SET_COMPANY_TYPE`
