export const PREFIX = 'SURVEY'
export const TECHNOLOGY_CONSTRUCTION = 'TECHNOLOGY_CONSTRUCTION'

export const SURVEY_PAGE_REQUEST = `${PREFIX}_PAGE_REQUEST`

export const SURVEY_SET_COMPANY_CATEGORY = `${PREFIX}_SET_COMPANY_CATEGORY`
export const SURVEY_SET_COMPANY_TYPE = `${PREFIX}_SET_COMPANY_TYPE`
export const SURVEY_SET_CONSTRUCTION_PRODUCT_TYPE = `${PREFIX}_SET_CONSTRUCTION_PRODUCT_TYPE`
export const SURVEY_SET_CONSTRUCTION_PROJECT_COST = `${PREFIX}_SET_CONSTRUCTION_PROJECT_COST`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_ASSESSMENT = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_ASSESSMENT`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_BENEFIT = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_BENEFIT`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_CATEGORY = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_CATEGORY`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_COST = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_COST`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_HUMAN_RESOURCE = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_HUMAN_RESOURCE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_INNOVATION_CATEGORY = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_INNOVATION_CATEGORY`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_INNOVATION_ORIGIN = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_INNOVATION_ORIGIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_OBSTACLE = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_OBSTACLE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_ORIGIN = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_ORIGIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_OWNER = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_OWNER`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_PRIMARY_TYPE = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_PRIMARY_TYPE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_STAGE = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_STAGE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_SUCCESS_FACTOR = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_SUCCESS_FACTOR`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_SUPPLY_CHAIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN_ORIGIN = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_SUPPLY_CHAIN_ORIGIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_TYPE = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_TYPE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_SUPPORT = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_SUPPORT`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_LEVEL = `${PREFIX}_SET_${TECHNOLOGY_CONSTRUCTION}_LEVEL`
export const SURVEY_SET_INTELLECTUAL_PROPERTY_RIGHT = `${PREFIX}_SET_INTELLECTUAL_PROPERTY_RIGHT`

export const SURVEY_ON_CLICK_SUBMIT_SURVEY = `${PREFIX}_ON_CLICK_SUBMIT_SURVEY`
