export const PREFIX = 'SURVEY'
export const TECHNOLOGY_CONSTRUCTION = 'TECHNOLOGY_CONSTRUCTION'

export const SURVEY_PAGE_REQUEST = `${PREFIX}_PAGE_REQUEST`

export const SURVEY_SET_COMPANY_CATEGORY = `${PREFIX}_SET_COMPANY_CATEGORY`
export const SURVEY_SET_COMPANY_TYPE = `${PREFIX}_SET_COMPANY_TYPE`
export const SURVEY_SET_CONSTRUCTION_PRODUCT_TYPE = `${PREFIX}_SET_CONSTRUCTION_PRODUCT_TYPE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_ASSESSMENT = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_ASSESSMENT`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_ASSESSMENT_METHOD = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_ASSESSMENT_METHOD`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_BENEFIT = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_BENEFIT`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_CATEGORY = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_CATEGORY`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_COST = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_COST`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_HUMAN_RESOURCE = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_HUMAN_RESOURCE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_INOVATION_CATEGORY = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_INOVATION_CATEGORY`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_INOVATION_ORIGIN = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_INOVATION_ORIGIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_OBSTACLE = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_OBSTACLE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_ORIGIN = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_ORIGIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_OWNER = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_OWNER`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_PRIMARY_TYPE = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_PRIMARY_TYPE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_STAGE = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_STAGE`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_SUCCESS_FACTOR = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_SUCCESS_FACTOR`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_SUPPLY_CHAIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_SUPPLY_CHAIN_ORIGIN = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_SUPPLY_CHAIN_ORIGIN`
export const SURVEY_SET_TECHNOLOGY_CONSTRUCTION_TYPE = `${PREFIX}_${TECHNOLOGY_CONSTRUCTION}_TYPE`
